class SurahMetadata {
  final int id;
  final String arabicName;
  final String englishName;
  final String turkishName;
  final String revelationType;
  final int ayahsCount;

  const SurahMetadata({
    required this.id,
    required this.arabicName,
    required this.englishName,
    required this.turkishName,
    required this.revelationType,
    required this.ayahsCount,
  });
}

const List<SurahMetadata> surahList = [
  SurahMetadata(id: 1, arabicName: "سُورَةُ ٱلْفَاتِحَةِ", englishName: "Al-Faatiha", turkishName: "Fâtiha", revelationType: "Meccan", ayahsCount: 7),
  SurahMetadata(id: 2, arabicName: "سُورَةُ البَقَرَةِ", englishName: "Al-Baqara", turkishName: "Bakara", revelationType: "Medinan", ayahsCount: 286),
  SurahMetadata(id: 3, arabicName: "سُورَةُ آلِ عِمۡرَانَ", englishName: "Aal-i-Imraan", turkishName: "Âl-i İmrân", revelationType: "Medinan", ayahsCount: 200),
  SurahMetadata(id: 4, arabicName: "سُورَةُ النِّسَاءِ", englishName: "An-Nisaa", turkishName: "Nisâ", revelationType: "Medinan", ayahsCount: 176),
  SurahMetadata(id: 5, arabicName: "سُورَةُ المَائـِدَةِ", englishName: "Al-Maaida", turkishName: "Mâide", revelationType: "Medinan", ayahsCount: 120),
  SurahMetadata(id: 6, arabicName: "سُورَةُ الأَنۡعَامِ", englishName: "Al-An'aam", turkishName: "En'âm", revelationType: "Meccan", ayahsCount: 165),
  SurahMetadata(id: 7, arabicName: "سُورَةُ الأَعۡرَافِ", englishName: "Al-A'raaf", turkishName: "A'râf", revelationType: "Meccan", ayahsCount: 206),
  SurahMetadata(id: 8, arabicName: "سُورَةُ الأَنفَالِ", englishName: "Al-Anfaal", turkishName: "Enfâl", revelationType: "Medinan", ayahsCount: 75),
  SurahMetadata(id: 9, arabicName: "سُورَةُ التَّوۡبَةِ", englishName: "At-Tawba", turkishName: "Tevbe", revelationType: "Medinan", ayahsCount: 129),
  SurahMetadata(id: 10, arabicName: "سُورَةُ يُونُسَ", englishName: "Yunus", turkishName: "Yûnus", revelationType: "Meccan", ayahsCount: 109),
  SurahMetadata(id: 11, arabicName: "سُورَةُ هُودٍ", englishName: "Hud", turkishName: "Hûd", revelationType: "Meccan", ayahsCount: 123),
  SurahMetadata(id: 12, arabicName: "سُورَةُ يُوسُفَ", englishName: "Yusuf", turkishName: "Yûsuf", revelationType: "Meccan", ayahsCount: 111),
  SurahMetadata(id: 13, arabicName: "سُورَةُ الرَّعۡدِ", englishName: "Ar-Ra'd", turkishName: "Ra'd", revelationType: "Medinan", ayahsCount: 43),
  SurahMetadata(id: 14, arabicName: "سُورَةُ إِبۡرَاهِيمَ", englishName: "Ibrahim", turkishName: "İbrâhîm", revelationType: "Meccan", ayahsCount: 52),
  SurahMetadata(id: 15, arabicName: "سُورَةُ الحِجۡرِ", englishName: "Al-Hijr", turkishName: "Hicr", revelationType: "Meccan", ayahsCount: 99),
  SurahMetadata(id: 16, arabicName: "سُورَةُ النَّحۡلِ", englishName: "An-Nahl", turkishName: "Nahl", revelationType: "Meccan", ayahsCount: 128),
  SurahMetadata(id: 17, arabicName: "سُورَةُ الإِسۡرَاءِ", englishName: "Al-Israa", turkishName: "İsrâ", revelationType: "Meccan", ayahsCount: 111),
  SurahMetadata(id: 18, arabicName: "سُورَةُ الكَهۡفِ", englishName: "Al-Kahf", turkishName: "Kehf", revelationType: "Meccan", ayahsCount: 110),
  SurahMetadata(id: 19, arabicName: "سُورَةُ مَرۡيَمَ", englishName: "Maryam", turkishName: "Meryem", revelationType: "Meccan", ayahsCount: 98),
  SurahMetadata(id: 20, arabicName: "سُورَةُ طه", englishName: "Taa-Haa", turkishName: "Tâhâ", revelationType: "Meccan", ayahsCount: 135),
  SurahMetadata(id: 21, arabicName: "سُورَةُ الأَنبِيَاءِ", englishName: "Al-Anbiyaa", turkishName: "Enbiyâ", revelationType: "Meccan", ayahsCount: 112),
  SurahMetadata(id: 22, arabicName: "سُورَةُ الحَجِّ", englishName: "Al-Hajj", turkishName: "Hac", revelationType: "Medinan", ayahsCount: 78),
  SurahMetadata(id: 23, arabicName: "سُورَةُ المُؤۡمِنُونَ", englishName: "Al-Muminoon", turkishName: "Mü'minûn", revelationType: "Meccan", ayahsCount: 118),
  SurahMetadata(id: 24, arabicName: "سُورَةُ النُّورِ", englishName: "An-Noor", turkishName: "Nûr", revelationType: "Medinan", ayahsCount: 64),
  SurahMetadata(id: 25, arabicName: "سُورَةُ الفُرۡقَانِ", englishName: "Al-Furqaan", turkishName: "Furkân", revelationType: "Meccan", ayahsCount: 77),
  SurahMetadata(id: 26, arabicName: "سُورَةُ الشُّعَرَاءِ", englishName: "Ash-Shu'araa", turkishName: "Şuarâ", revelationType: "Meccan", ayahsCount: 227),
  SurahMetadata(id: 27, arabicName: "سُورَةُ النَّمۡلِ", englishName: "An-Naml", turkishName: "Neml", revelationType: "Meccan", ayahsCount: 93),
  SurahMetadata(id: 28, arabicName: "سُورَةُ القَصَصِ", englishName: "Al-Qasas", turkishName: "Kasas", revelationType: "Meccan", ayahsCount: 88),
  SurahMetadata(id: 29, arabicName: "سُورَةُ العَنكَبُوتِ", englishName: "Al-Ankaboot", turkishName: "Ankebût", revelationType: "Meccan", ayahsCount: 69),
  SurahMetadata(id: 30, arabicName: "سُورَةُ الرُّومِ", englishName: "Ar-Room", turkishName: "Rûm", revelationType: "Meccan", ayahsCount: 60),
  SurahMetadata(id: 31, arabicName: "سُورَةُ لُقۡمَانَ", englishName: "Luqman", turkishName: "Lokmân", revelationType: "Meccan", ayahsCount: 34),
  SurahMetadata(id: 32, arabicName: "سُورَةُ السَّجۡدَةِ", englishName: "As-Sajda", turkishName: "Secde", revelationType: "Meccan", ayahsCount: 30),
  SurahMetadata(id: 33, arabicName: "سُورَةُ الأَحۡزَابِ", englishName: "Al-Ahzaab", turkishName: "Ahzâb", revelationType: "Medinan", ayahsCount: 73),
  SurahMetadata(id: 34, arabicName: "سُورَةُ سَبَإٍ", englishName: "Saba", turkishName: "Sebe'", revelationType: "Meccan", ayahsCount: 54),
  SurahMetadata(id: 35, arabicName: "سُورَةُ فَاطِرٍ", englishName: "Faatir", turkishName: "Fâtır", revelationType: "Meccan", ayahsCount: 45),
  SurahMetadata(id: 36, arabicName: "سُورَةُ يسٓ", englishName: "Yaseen", turkishName: "Yâsîn", revelationType: "Meccan", ayahsCount: 83),
  SurahMetadata(id: 37, arabicName: "سُورَةُ الصَّافَّاتِ", englishName: "As-Saaffaat", turkishName: "Sâffât", revelationType: "Meccan", ayahsCount: 182),
  SurahMetadata(id: 38, arabicName: "سُورَةُ صٓ", englishName: "Saad", turkishName: "Sâd", revelationType: "Meccan", ayahsCount: 88),
  SurahMetadata(id: 39, arabicName: "سُورَةُ الزُّمَرِ", englishName: "Az-Zumar", turkishName: "Zümer", revelationType: "Meccan", ayahsCount: 75),
  SurahMetadata(id: 40, arabicName: "سُورَةُ غَافِرٍ", englishName: "Ghafir", turkishName: "Mü'min (Gâfir)", revelationType: "Meccan", ayahsCount: 85),
  SurahMetadata(id: 41, arabicName: "سُورَةُ فُصِّلَتۡ", englishName: "Fussilat", turkishName: "Fussilet", revelationType: "Meccan", ayahsCount: 54),
  SurahMetadata(id: 42, arabicName: "سُورَةُ الشُّورَىٰ", englishName: "Ash-Shura", turkishName: "Şûrâ", revelationType: "Meccan", ayahsCount: 53),
  SurahMetadata(id: 43, arabicName: "سُورَةُ الزُّخۡرُفِ", englishName: "Az-Zukhruf", turkishName: "Zuhruf", revelationType: "Meccan", ayahsCount: 89),
  SurahMetadata(id: 44, arabicName: "سُورَةُ الدُّخَانِ", englishName: "Ad-Dukhaan", turkishName: "Duhân", revelationType: "Meccan", ayahsCount: 59),
  SurahMetadata(id: 45, arabicName: "سُورَةُ الجَاثِيَةِ", englishName: "Al-Jaathiya", turkishName: "Câsiye", revelationType: "Meccan", ayahsCount: 37),
  SurahMetadata(id: 46, arabicName: "سُورَةُ الأَحۡقَافِ", englishName: "Al-Ahqaf", turkishName: "Ahkâf", revelationType: "Meccan", ayahsCount: 35),
  SurahMetadata(id: 47, arabicName: "سُورَةُ مُحَمَّدٍ", englishName: "Muhammad", turkishName: "Muhammed", revelationType: "Medinan", ayahsCount: 38),
  SurahMetadata(id: 48, arabicName: "سُورَةُ الفَتۡحِ", englishName: "Al-Fath", turkishName: "Fetih", revelationType: "Medinan", ayahsCount: 29),
  SurahMetadata(id: 49, arabicName: "سُورَةُ الحُجُرَاتِ", englishName: "Al-Hujuraat", turkishName: "Hucurât", revelationType: "Medinan", ayahsCount: 18),
  SurahMetadata(id: 50, arabicName: "سُورَةُ قٓ", englishName: "Qaaf", turkishName: "Kâf", revelationType: "Meccan", ayahsCount: 45),
  SurahMetadata(id: 51, arabicName: "سُورَةُ الذَّارِيَاتِ", englishName: "Adh-Dhaariyat", turkishName: "Zâriyât", revelationType: "Meccan", ayahsCount: 60),
  SurahMetadata(id: 52, arabicName: "سُورَةُ الطُّورِ", englishName: "At-Tur", turkishName: "Tûr", revelationType: "Meccan", ayahsCount: 49),
  SurahMetadata(id: 53, arabicName: "سُورَةُ النَّجۡمِ", englishName: "An-Najm", turkishName: "Necm", revelationType: "Meccan", ayahsCount: 62),
  SurahMetadata(id: 54, arabicName: "سُورَةُ القَمَرِ", englishName: "Al-Qamar", turkishName: "Kamer", revelationType: "Meccan", ayahsCount: 55),
  SurahMetadata(id: 55, arabicName: "سُورَةُ الرَّحۡمَٰن", englishName: "Ar-Rahmaan", turkishName: "Rahmân", revelationType: "Medinan", ayahsCount: 78),
  SurahMetadata(id: 56, arabicName: "سُورَةُ الوَاقِعَةِ", englishName: "Al-Waaqia", turkishName: "Vâkıa", revelationType: "Meccan", ayahsCount: 96),
  SurahMetadata(id: 57, arabicName: "سُورَةُ الحَدِيدِ", englishName: "Al-Hadid", turkishName: "Hadîd", revelationType: "Medinan", ayahsCount: 29),
  SurahMetadata(id: 58, arabicName: "سُورَةُ المُجَادلَةِ", englishName: "Al-Mujaadila", turkishName: "Mücâdele", revelationType: "Medinan", ayahsCount: 22),
  SurahMetadata(id: 59, arabicName: "سُورَةُ الحَشۡرِ", englishName: "Al-Hashr", turkishName: "Haşr", revelationType: "Medinan", ayahsCount: 24),
  SurahMetadata(id: 60, arabicName: "سُورَةُ المُمۡتَحنَةِ", englishName: "Al-Mumtahana", turkishName: "Mümtehine", revelationType: "Medinan", ayahsCount: 13),
  SurahMetadata(id: 61, arabicName: "سُورَةُ الصَّفِّ", englishName: "As-Saff", turkishName: "Saff", revelationType: "Medinan", ayahsCount: 14),
  SurahMetadata(id: 62, arabicName: "سُورَةُ الجُمُعَةِ", englishName: "Al-Jumu'a", turkishName: "Cuma", revelationType: "Medinan", ayahsCount: 11),
  SurahMetadata(id: 63, arabicName: "سُورَةُ المُنَافِقُونَ", englishName: "Al-Munaafiqoon", turkishName: "Münâfikûn", revelationType: "Medinan", ayahsCount: 11),
  SurahMetadata(id: 64, arabicName: "سُورَةُ التَّغَابُنِ", englishName: "At-Taghaabun", turkishName: "Teğâbün", revelationType: "Medinan", ayahsCount: 18),
  SurahMetadata(id: 65, arabicName: "سُورَةُ الطَّلَاقِ", englishName: "At-Talaaq", turkishName: "Talâk", revelationType: "Medinan", ayahsCount: 12),
  SurahMetadata(id: 66, arabicName: "سُورَةُ التَّحۡرِيمِ", englishName: "At-Tahrim", turkishName: "Tahrîm", revelationType: "Medinan", ayahsCount: 12),
  SurahMetadata(id: 67, arabicName: "سُورَةُ المُلۡكِ", englishName: "Al-Mulk", turkishName: "Mülk", revelationType: "Meccan", ayahsCount: 30),
  SurahMetadata(id: 68, arabicName: "سُورَةُ القَلَمِ", englishName: "Al-Qalam", turkishName: "Kalem", revelationType: "Meccan", ayahsCount: 52),
  SurahMetadata(id: 69, arabicName: "سُورَةُ الحَاقَّةِ", englishName: "Al-Haaqqa", turkishName: "Hâkka", revelationType: "Meccan", ayahsCount: 52),
  SurahMetadata(id: 70, arabicName: "سُورَةُ المَعَارِجِ", englishName: "Al-Ma'aarij", turkishName: "Meâric", revelationType: "Meccan", ayahsCount: 44),
  SurahMetadata(id: 71, arabicName: "سُورَةُ نُوحٍ", englishName: "Nooh", turkishName: "Nûh", revelationType: "Meccan", ayahsCount: 28),
  SurahMetadata(id: 72, arabicName: "سُورَةُ الجِنِّ", englishName: "Al-Jinn", turkishName: "Cin", revelationType: "Meccan", ayahsCount: 28),
  SurahMetadata(id: 73, arabicName: "سُورَةُ المُزَّمِّلِ", englishName: "Al-Muzzammil", turkishName: "Müzzemmil", revelationType: "Meccan", ayahsCount: 20),
  SurahMetadata(id: 74, arabicName: "سُورَةُ المُدَّثِّرِ", englishName: "Al-Muddaththir", turkishName: "Müddessir", revelationType: "Meccan", ayahsCount: 56),
  SurahMetadata(id: 75, arabicName: "سُورَةُ القِيَامَةِ", englishName: "Al-Qiyaama", turkishName: "Kıyâme", revelationType: "Meccan", ayahsCount: 40),
  SurahMetadata(id: 76, arabicName: "سُورَةُ الإِنسَانِ", englishName: "Al-Insaan", turkishName: "İnsan", revelationType: "Medinan", ayahsCount: 31),
  SurahMetadata(id: 77, arabicName: "سُورَةُ المُرۡسَلَاتِ", englishName: "Al-Mursalaat", turkishName: "Mürselât", revelationType: "Meccan", ayahsCount: 50),
  SurahMetadata(id: 78, arabicName: "سُورَةُ النَّبَإِ", englishName: "An-Naba", turkishName: "Nebe", revelationType: "Meccan", ayahsCount: 40),
  SurahMetadata(id: 79, arabicName: "سُورَةُ النَّازِعَاتِ", englishName: "An-Naazi'aat", turkishName: "Nâziât", revelationType: "Meccan", ayahsCount: 46),
  SurahMetadata(id: 80, arabicName: "سُورَةُ عَبَسَ", englishName: "Abasa", turkishName: "Abese", revelationType: "Meccan", ayahsCount: 42),
  SurahMetadata(id: 81, arabicName: "سُورَةُ التَّكۡوِيرِ", englishName: "At-Takwir", turkishName: "Tekvîr", revelationType: "Meccan", ayahsCount: 29),
  SurahMetadata(id: 82, arabicName: "سُورَةُ الانفِطَارِ", englishName: "Al-Infitaar", turkishName: "İnfitâr", revelationType: "Meccan", ayahsCount: 19),
  SurahMetadata(id: 83, arabicName: "سُورَةُ المُطَفِّفِينَ", englishName: "Al-Mutaffifin", turkishName: "Mutaffifîn", revelationType: "Meccan", ayahsCount: 36),
  SurahMetadata(id: 84, arabicName: "سُورَةُ الانشِقَاقِ", englishName: "Al-Inshiqaaq", turkishName: "İnşikâk", revelationType: "Meccan", ayahsCount: 25),
  SurahMetadata(id: 85, arabicName: "سُورَةُ البُرُوجِ", englishName: "Al-Burooj", turkishName: "Bürûc", revelationType: "Meccan", ayahsCount: 22),
  SurahMetadata(id: 86, arabicName: "سُورَةُ الطَّارِقِ", englishName: "At-Taariq", turkishName: "Târık", revelationType: "Meccan", ayahsCount: 17),
  SurahMetadata(id: 87, arabicName: "سُورَةُ الأَعۡلَىٰ", englishName: "Al-A'laa", turkishName: "A'lâ", revelationType: "Meccan", ayahsCount: 19),
  SurahMetadata(id: 88, arabicName: "سُورَةُ الغَاشِيَةِ", englishName: "Al-Ghaashiya", turkishName: "Gâşiye", revelationType: "Meccan", ayahsCount: 26),
  SurahMetadata(id: 89, arabicName: "سُورَةُ الفَجۡرِ", englishName: "Al-Fajr", turkishName: "Fecr", revelationType: "Meccan", ayahsCount: 30),
  SurahMetadata(id: 90, arabicName: "سُورَةُ البَلَدِ", englishName: "Al-Balad", turkishName: "Beled", revelationType: "Meccan", ayahsCount: 20),
  SurahMetadata(id: 91, arabicName: "سُورَةُ الشَّمۡسِ", englishName: "Ash-Shams", turkishName: "Şems", revelationType: "Meccan", ayahsCount: 15),
  SurahMetadata(id: 92, arabicName: "سُورَةُ اللَّيۡلِ", englishName: "Al-Lail", turkishName: "Leyl", revelationType: "Meccan", ayahsCount: 21),
  SurahMetadata(id: 93, arabicName: "سُورَةُ الضُّحَىٰ", englishName: "Ad-Dhuhaa", turkishName: "Duhâ", revelationType: "Meccan", ayahsCount: 11),
  SurahMetadata(id: 94, arabicName: "سُورَةُ الشَّرۡحِ", englishName: "Ash-Sharh", turkishName: "İnşirâh", revelationType: "Meccan", ayahsCount: 8),
  SurahMetadata(id: 95, arabicName: "سُورَةُ التِّينِ", englishName: "At-Tin", turkishName: "Tîn", revelationType: "Meccan", ayahsCount: 8),
  SurahMetadata(id: 96, arabicName: "سُورَةُ العَلَقِ", englishName: "Al-Alaq", turkishName: "Alak", revelationType: "Meccan", ayahsCount: 19),
  SurahMetadata(id: 97, arabicName: "سُورَةُ القَدۡرِ", englishName: "Al-Qadr", turkishName: "Kadr", revelationType: "Meccan", ayahsCount: 5),
  SurahMetadata(id: 98, arabicName: "سُورَةُ البَيِّنَةِ", englishName: "Al-Bayyina", turkishName: "Beyyine", revelationType: "Medinan", ayahsCount: 8),
  SurahMetadata(id: 99, arabicName: "سُورَةُ الزَّلۡزَلَةِ", englishName: "Az-Zalzala", turkishName: "Zilzâl", revelationType: "Medinan", ayahsCount: 8),
  SurahMetadata(id: 100, arabicName: "سُورَةُ العَادِيَاتِ", englishName: "Al-Aadiyaat", turkishName: "Âdiyât", revelationType: "Meccan", ayahsCount: 11),
  SurahMetadata(id: 101, arabicName: "سُورَةُ القَارِعَةِ", englishName: "Al-Qaari'a", turkishName: "Kâria", revelationType: "Meccan", ayahsCount: 11),
  SurahMetadata(id: 102, arabicName: "سُورَةُ التَّكَاثُرِ", englishName: "At-Takaathur", turkishName: "Tekâsür", revelationType: "Meccan", ayahsCount: 8),
  SurahMetadata(id: 103, arabicName: "سُورَةُ العَصۡرِ", englishName: "Al-Asr", turkishName: "Asr", revelationType: "Meccan", ayahsCount: 3),
  SurahMetadata(id: 104, arabicName: "سُورَةُ الهُمَزَةِ", englishName: "Al-Humaza", turkishName: "Hümeze", revelationType: "Meccan", ayahsCount: 9),
  SurahMetadata(id: 105, arabicName: "سُورَةُ الفِيلِ", englishName: "Al-Fil", turkishName: "Fîl", revelationType: "Meccan", ayahsCount: 5),
  SurahMetadata(id: 106, arabicName: "سُورَةُ قُرَيۡشٍ", englishName: "Quraish", turkishName: "Kureyş", revelationType: "Meccan", ayahsCount: 4),
  SurahMetadata(id: 107, arabicName: "سُورَةُ المَاعُونِ", englishName: "Al-Maa'un", turkishName: "Mâûn", revelationType: "Meccan", ayahsCount: 7),
  SurahMetadata(id: 108, arabicName: "سُورَةُ الكَوۡثَرِ", englishName: "Al-Kawthar", turkishName: "Kevser", revelationType: "Meccan", ayahsCount: 3),
  SurahMetadata(id: 109, arabicName: "سُورَةُ الكَافِرُونَ", englishName: "Al-Kaafiroon", turkishName: "Kâfirûn", revelationType: "Meccan", ayahsCount: 6),
  SurahMetadata(id: 110, arabicName: "سُورَةُ النَّصۡرِ", englishName: "An-Nasr", turkishName: "Nasr", revelationType: "Medinan", ayahsCount: 3),
  SurahMetadata(id: 111, arabicName: "سُورَةُ المَسَدِ", englishName: "Al-Masad", turkishName: "Tebbet", revelationType: "Meccan", ayahsCount: 5),
  SurahMetadata(id: 112, arabicName: "سُورَةُ الإِخۡلَاصِ", englishName: "Al-Ikhlaas", turkishName: "İhlâs", revelationType: "Meccan", ayahsCount: 4),
  SurahMetadata(id: 113, arabicName: "سُورَةُ الفَلَقِ", englishName: "Al-Falaq", turkishName: "Felak", revelationType: "Meccan", ayahsCount: 5),
  SurahMetadata(id: 114, arabicName: "سُورَةُ النَّاسِ", englishName: "An-Naas", turkishName: "Nâs", revelationType: "Meccan", ayahsCount: 6),
];
